### ISSUE TITLE
ModuleNotFoundError: No module named 'zapv2'

### ISSUE THREAD

**Issue by M0dred** [secdec/adapt#9]
python3 adapt.py 

It seems that you have not run the installer script.
We will now run that briefly before continuing.
This script should no longer be run as root
Traceback (most recent call last):
  File "adapt.py", line 47, in <module>
    from zap_interface import AdaptZap
  File "/opt/github/adapt/src/zap_interface.py", line 23, in <module>
    from zapv2 import ZAPv2
ModuleNotFoundError: No module named 'zapv2'
root@K0walski:/opt/github/adapt# pip3 install zapv2
Collecting zapv2
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/zapv2/

**Comment by matthewD-AVI** [comment]
Hello M0rded,

Thank you for bringing this to my attention. I will look into this right away and will hopefully have a resolution shortly. I have an idea of  what may be the problem and will investigate further.

**Comment by matthewD-AVI** [comment]
@M0dred  I made some minor changes to the isntall script to fix some new dependency issues.
It also seems you were trying to run adapt.py/install.sh as root. These scripts should no longer be run as root. I would re-run install.sh without root access.

> root@K0walski:/opt/github/adapt# pip3 install zapv2

The proper command to install zapv2 would be `pip3 install python-owasp-zap-v2.4` but should be installed through the install.sh script
